# Generated by Django 4.1.6 on 2023-06-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=25, unique=True)),
                ('price', models.IntegerField()),
                ('product_image', models.ImageField(null=True, upload_to='media/product_image/')),
                ('catagory', models.CharField(max_length=25, unique=True)),
            ],
        ),
    ]
