# Generated by Django 4.1.6 on 2023-06-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0003_alter_user_info_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='image',
            field=models.ImageField(max_length=250, null=True, upload_to='image/'),
        ),
    ]
