# Generated by Django 4.1.6 on 2023-06-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0004_alter_user_info_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='image',
            field=models.ImageField(null=True, upload_to='media/image/'),
        ),
    ]
