# Generated by Django 4.1.6 on 2023-06-11 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0005_alter_user_info_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='user_name',
            new_name='username',
        ),
    ]
