# Generated by Django 4.1.6 on 2023-06-12 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0006_rename_user_name_user_info_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_info',
            new_name='User_infoo',
        ),
    ]
