# Generated by Django 4.1.6 on 2023-06-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0007_rename_user_info_user_infoo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_infoo',
            name='email',
            field=models.EmailField(max_length=25, unique=True),
        ),
    ]
