# Generated by Django 4.1.6 on 2023-06-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0008_alter_user_infoo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_infoo',
            name='username',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
