# Generated by Django 4.1.6 on 2023-06-17 11:18

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0009_alter_user_infoo_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_infoo',
            name='user_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='username', unique=True),
        ),
    ]
