# Generated by Django 4.1.6 on 2023-06-19 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0010_user_infoo_user_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_infoo',
            name='user_slug',
        ),
    ]
