# Generated by Django 4.1.6 on 2023-08-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('p_name', models.CharField(max_length=25, unique=True)),
                ('unit', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
